### ISSUE TITLE
trace.py

### ISSUE THREAD

**Issue by kooBH** [kooBH/End-to-End-VAD#2]
```
loading pre-trainded model..
Traceback (most recent call last):
  File "trace.py", line 30, in <module>
    net.load_state_dict(torch.load(args.input))
  File "/home/kbh/E2EVAD/lib/python3.5/site-packages/torch/nn/modules/module.py", line 830, in 
load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepVAD_video:
        Missing key(s) in state_dict: "features.0.weight", "features.1.bias", "features.1.running_var",
 "features.1.running_mean", "features.1.weight", "features.4.0.conv1.weight", 
"features.4.0.bn1.bias", "features.4.0.bn1.running_var", "features.4.0.bn1.running_mean", 
"features.4.0.bn1.weight", "features.4.0.conv2.weight", "features.4.0.bn2.bias", 
"features.4.0.bn2.running_var", "features.4.0.bn2.running_mean", "features.4.0.bn2.weight", 
"features.4.1.conv1.weight", "features.4.1.bn1.bias", "features.4.1.bn1.running_var", 
"features.4.1.bn1.running_mean", "features.4.1.bn1.weight", "features.4.1.conv2.weight", 
"features.4.1.bn2.bias", "features.4.1.bn2.running_var", "features.4.1.bn2.running_mean", 
"features.4.1.bn2.weight", "features.5.0.conv1.weight", "features.5.0.bn1.bias", 
"features.5.0.bn1.running_var", "features.5.0.bn1.running_mean", "features.5.0.bn1.weight", 
"features.5.0.conv2.weight", "features.5.0.bn2.bias", "features.5.0.bn2.running_var", 
"features.5.0.bn2.running_mean", "features.5.0.bn2.weight", "features.5.0.downsample.0.weight", 
"features.5.0.downsample.1.bias", "features.5.0.downsample.1.running_var", 
"features.5.0.downsample.1.running_mean", "features.5.0.downsample.1.weight", 
"features.5.1.conv1.weight", "features.5.1.bn1.bias", "features.5.1.bn1.running_var", 
"features.5.1.bn1.running_mean", "features.5.1.bn1.weight", "features.5.1.conv2.weight", 
"features.5.1.bn2.bias", "features.5.1.bn2.running_var", "features.5.1.bn2.running_mean", 
"features.5.1.bn2.weight", "features.6.0.conv1.weight", "features.6.0.bn1.bias", 
"features.6.0.bn1.running_var", "features.6.0.bn1.running_mean", "features.6.0.bn1.weight", 
"features.6.0.conv2.weight", "features.6.0.bn2.bias", "features.6.0.bn2.running_var", 
"features.6.0.bn2.running_mean", "features.6.0.bn2.weight", "features.6.0.downsample.0.weight", 
"features.6.0.downsample.1.bias", "features.6.0.downsample.1.running_var", 
"features.6.0.downsample.1.running_mean", "features.6.0.downsample.1.weight", 
"features.6.1.conv1.weight", "features.6.1.bn1.bias", "features.6.1.bn1.running_var", 
"features.6.1.bn1.running_mean", "features.6.1.bn1.weight", "features.6.1.conv2.weight", 
"features.6.1.bn2.bias", "features.6.1.bn2.running_var", "features.6.1.bn2.running_mean", 
"features.6.1.bn2.weight", "features.7.0.conv1.weight", "features.7.0.bn1.bias", 
"features.7.0.bn1.running_var", "features.7.0.bn1.running_mean", "features.7.0.bn1.weight", 
"features.7.0.conv2.weight", "features.7.0.bn2.bias", "features.7.0.bn2.running_var", 
"features.7.0.bn2.running_mean", "features.7.0.bn2.weight", "features.7.0.downsample.0.weight", 
"features.7.0.downsample.1.bias", "features.7.0.downsample.1.running_var", 
"features.7.0.downsample.1.running_mean", "features.7.0.downsample.1.weight", 
"features.7.1.conv1.weight", "features.7.1.bn1.bias", "features.7.1.bn1.running_var", 
"features.7.1.bn1.running_mean", "features.7.1.bn1.weight", "features.7.1.conv2.weight", 
"features.7.1.bn2.bias", "features.7.1.bn2.running_var", "features.7.1.bn2.running_mean", 
"features.7.1.bn2.weight", "lstm_video.bias_ih_l1", "lstm_video.weight_ih_l0", 
"lstm_video.weight_hh_l1", "lstm_video.weight_hh_l0", "lstm_video.weight_ih_l1", 
"lstm_video.bias_hh_l1", "lstm_video.bias_ih_l0", "lstm_video.bias_hh_l0", "vad_video.bias", 
"vad_video.weight".
        Unexpected key(s) in state_dict: "accuracy", "best_accuracy", "epoch", "state_dict", "arch", "optimizer".
```
첫 시도는 실패

**Comment by kooBH** [comment]
https://jangjy.tistory.com/318 에서는 모델이 다르면 이렇게 된다는데. 같은 
```python
utils.import_network('Vedio')
```

로 모델을 불러서 돌리는데 다를 수가 없지 않은가

**Comment by kooBH** [comment]
state가 제대로 저장되지 않았다.
```net.staet_dict()``` 를 저장해야하는데 그냥 ```net```을 저장했다. 

```
tracing
Traceback (most recent call last):
  File "trace.py", line 36, in <module>
    traced_model = torch.jit.trace(net, trace_input)
  File "/home/kbh/E2EVAD/lib/python3.5/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/kbh/E2EVAD/lib/python3.5/site-packages/torch/jit/__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/home/kbh/E2EVAD/lib/python3.5/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/kbh/E2EVAD/lib/python3.5/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'h'
```

이런 에러가 발생.  

forward 가 
```python
    def forward(self, x, h):
```
이다. h를 같이 넣어 줘야한다. 

```python
    states = net.init_hidden(is_train=True)
```
를 같이 넣어주자.

```
    batch,frames,channels,height,width = x.squeeze().size()
ValueError: not enough values to unpack (expected 5, got 3)
```

batch,frame을 넣어줘야한다. 
+ 실사용 시에는 batch로 하지 않는데 모델 학습은 batch로 한다. 이게 따로 사용이 가능한 것인가
+ frame이 ```depth_time``` 일까. 

일단 지금 상태에서는 학습할 때와 같은 값을 넣어야한다. 

```python
    trace_input=torch.rand(16,15,3,size,size).cuda()
```
하지만 out of memory 발생. 3GB가 있고 730MB 할당해야하는데 에러가 발생했다. 이상하다. 

https://discuss.pytorch.org/t/unable-to-allocate-cuda-memory-when-there-is-enough-of-cached-memory/33296

여기선 VRAM frag 때문이라는 데 600,400,100 MB 씩 3개가 쓰는데 이걸로 3GB가 730MB 쓸 자리 없도록 frag가 된다고?

일단 서버에서 돌려서 TorchScript를 만들어지는 것 확인 하였으니 파이썬에서 테스트를 해보자.  #3
